	.align 2
voicegroupInst47:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_c2, 255, 253, 0, 216	@ 127/ 35/  1/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_g2, 255, 253, 0, 216	@ 127/ 35/  1/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_c3, 255, 253, 0, 216	@ 127/ 35/  1/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_g3, 255, 253, 0, 216	@ 127/ 35/  1/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_c4, 255, 253, 0, 216	@ 127/ 35/  1/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_g4, 255, 253, 0, 216	@ 127/ 35/  1/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_c5, 255, 253, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_bw_piano1_g5, 255, 253, 0, 216
