	.align 2
voicegroupInst5:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_harpsichord_a3, 255, 251, 0, 197	@ 127/ 60/  1/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_harpsichord_a3, 255, 251, 0, 197	@ 127/ 60/  1/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_harpsichord_f4, 255, 251, 0, 197	@ 127/ 60/  1/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_harpsichord_d5, 255, 251, 0, 197	@ 127/ 60/  1/118/ 64
