	.align 2
voicegroupInst57:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_underwater_fx_c3, 255, 249, 0, 178	@ 127/ 75/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_underwater_fx_c3, 255, 249, 0, 178	@ 127/ 75/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_underwater_fx_c4, 255, 249, 0, 178	@ 127/ 75/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_underwater_fx_c6, 255, 249, 0, 178	@ 127/ 75/  1/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_underwater_fx_c6, 255, 249, 0, 178	@ 127/ 75/  1/120/ 64
