	.align 2
voicegroupInst9:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_xylophone2_c4, 255, 250, 0, 208	@ 127/ 72/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_xylophone2_a4, 255, 250, 0, 208	@ 127/ 72/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_xylophone2_f5, 255, 250, 0, 208	@ 127/ 72/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_xylophone2_f5, 255, 250, 0, 208	@ 127/ 72/  1/116/ 64
