	.align 2
voicegroupInst64:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_pipe_organ_c4, 255, 242, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_bw_pipe_organ_c4, 255, 242, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_bw_pipe_organ_c4, 255, 242, 191, 208	@ 127/100/110/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_pipe_organ_a4, 255, 242, 191, 208	@ 127/100/110/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_pipe_organ_f5, 255, 242, 191, 208	@ 127/100/110/116/ 64
