	.align 2
voicegroupDrum8:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 60, 64, DirectSoundWaveData_bw_sd90_power_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_sd90_power_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_sd90_power_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_sd90_power_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_sd90_power_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 225, 127, 208	@ 127/114/ 90/116/ 64
	voice_directsound 60, 30, DirectSoundWaveData_hg_135tom, 255, 0, 255, 208	@ 127/127/127/116/ 30
	voice_directsound 60, 80, DirectSoundWaveData_hg_062chh, 255, 112, 0, 208	@ 127/124/  0/116/ 80
	voice_directsound 60, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 208	@ 127/127/127/116/ 40
	voice_directsound 61, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 208	@ 127/127/127/116/ 40	@ not used
	voice_directsound 62, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 208	@ 127/127/127/116/ 40	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_hg_063ohh, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_hg_063ohh, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_hg_063ohh, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 60, 90, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 90
	voice_directsound 61, 40, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 40
