	.align 2
voicegroupDrum3::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 60, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_room_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 57, 30, DirectSoundWaveData_bw_room_tom_low, 255, 0, 255, 208	@ 127/127/127/116/ 30
	voice_directsound 60, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80
	voice_directsound 60, 40, DirectSoundWaveData_bw_room_tom_low, 255, 0, 255, 208	@ 127/127/127/116/ 40
	voice_directsound 61, 40, DirectSoundWaveData_bw_room_tom_low, 255, 0, 255, 208	@ 127/127/127/116/ 40
	voice_directsound 56, 50, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/ 50
	voice_directsound 60, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 60, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 61, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 62, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 63, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 64, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 65, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 66, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 67, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 68, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 69, 100, DirectSoundWaveData_bw_room_tom_high, 255, 0, 255, 208	@ 127/127/127/116/100
	voice_directsound 60, 40, DirectSoundWaveData_bw_room_crash_cymbal, 255, 251, 0, 208	@ 127/ 62/  0/116/ 40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
