	.align 2
voicegroupDrum16:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_drum_loop_hof, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 61, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_rimshot_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_rimshot_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_rimshot_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_rimshot_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80	@ not used
	voice_directsound 63, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_bw_909_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_909_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_hg_033orccym, 255, 250, 0, 216	@ 127/ 70/  0/114/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 65, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 66, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 67, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64	@ not used
	voice_directsound 60, 40, DirectSoundWaveData_bw_pop_crash_18, 255, 251, 0, 208	@ 127/ 62/  0/116/ 40
	voice_directsound 61, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105
	voice_directsound 62, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 63, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 64, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 65, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 66, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 67, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 68, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 69, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 70, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 71, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 72, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 73, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 74, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 75, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 76, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 77, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 78, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 79, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 80, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 81, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 82, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 83, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 84, 105, DirectSoundWaveData_bw_pop_crash_17, 255, 251, 0, 208	@ 127/ 62/  0/116/105	@ not used
	voice_directsound 60, 30, DirectSoundWaveData_bw_tambourine, 255, 222, 227, 208	@ 127/115/120/116/ 30
	voice_directsound 61, 30, DirectSoundWaveData_bw_tambourine, 255, 222, 227, 208	@ 127/115/120/116/ 30	@ not used
	voice_directsound 62, 30, DirectSoundWaveData_bw_tambourine, 255, 222, 227, 208	@ 127/115/120/116/ 30	@ not used
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 249, 0, 197	@ 127/ 80/  0/118/ 44
