	.align 2
voicegroupInst44:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchestra_strings_f2, 255, 242, 191, 197	@ 127/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchestra_strings_c3, 255, 242, 191, 197	@ 127/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchestra_strings_a3, 255, 242, 191, 197	@ 127/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchestra_strings_f4, 255, 242, 191, 197	@ 127/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_orchestra_strings_f4, 255, 242, 191, 197
