	.align 2
voicegroupDrum12:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 3, 0, 227, 178	@   4/127/120/120/ 64
	voice_directsound 49, 64, DirectSoundWaveData_dp_reverscyn_16, 3, 0, 227, 178	@   4/127/120/120/ 64	@ not used
	voice_directsound 50, 64, DirectSoundWaveData_dp_reverscyn_16, 3, 0, 227, 178	@   4/127/120/120/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 65, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 66, 64, DirectSoundWaveData_bw_rim_hit, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_pop_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_pop_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_pop_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30
	voice_directsound 61, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 62, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 63, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 64, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 65, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 66, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 67, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 68, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 69, 30, DirectSoundWaveData_bw_claps, 255, 0, 227, 208	@ 127/127/120/116/ 30	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_hg_032crash, 255, 249, 0, 216	@ 127/ 80/  0/114/ 64
