	.align 2
voicegroupInst43:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_sitar_c3, 255, 252, 0, 208	@ 127/ 55/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_sitar_a3, 255, 252, 0, 197	@ 127/ 55/  1/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_sitar_f4, 255, 252, 0, 208	@ 127/ 55/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_sitar_d5, 255, 252, 0, 208	@ 127/ 55/  1/116/ 64
