	.align 2
voicegroupDrum10:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 48, 64, DirectSoundWaveData_bw_t9_clap, 255, 197, 227, 16	@ 127/120/120/126/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_t9_clap, 255, 197, 227, 16	@ 127/120/120/126/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_t9_snare, 255, 197, 227, 16	@ 127/120/120/126/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_t9_snare, 255, 197, 227, 16	@ 127/120/120/126/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_t9_snare, 255, 197, 227, 16	@ 127/120/120/126/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_dance_kick_crash, 255, 197, 227, 208	@ 127/120/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_dance_kick, 255, 197, 227, 208	@ 127/120/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_dance_kick, 255, 197, 227, 208	@ 127/120/120/116/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_dance_kick, 255, 197, 227, 208	@ 127/120/120/116/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_dance_kick, 255, 197, 227, 208	@ 127/120/120/116/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_dance_kick, 255, 197, 227, 208	@ 127/120/120/116/ 64	@ not used
	voice_directsound 65, 64, DirectSoundWaveData_bw_dance_kick, 255, 197, 227, 208	@ 127/120/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_dance_snare, 255, 0, 255, 0	@ 127/127/127/127/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 61, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64
	voice_directsound 65, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 66, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 67, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 68, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 69, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 70, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 71, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 72, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 73, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 74, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 75, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 76, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 77, 64, DirectSoundWaveData_bw_cowbell, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_dance_closed_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_dance_closed_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_dance_closed_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_dance_closed_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_dance_open_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_dance_open_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_dance_open_hihat, 255, 0, 255, 0	@ 127/127/127/127/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 64
	voice_directsound 61, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 216	@ 127/ 90/  0/114/ 64
