	.align 2
voicegroupInst53:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_nylon_string_guitar_g2, 255, 253, 6, 178	@ 127/ 42/ 20/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_nylon_string_guitar_g3, 255, 253, 6, 178	@ 127/ 42/ 20/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_nylon_string_guitar_e4, 255, 253, 6, 178	@ 127/ 42/ 20/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_nylon_string_guitar_e4, 255, 253, 6, 178	@ 127/ 42/ 20/120/ 64
