	.align 2
voicegroupInst16:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_bw_marschall_guitar_g2, 255, 254, 0, 48	@ 127/ 30/  1/125/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_marschall_guitar_g3, 255, 254, 0, 48	@ 127/ 30/  1/125/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_marschall_guitar_e4, 255, 254, 0, 48	@ 127/ 30/  1/125/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_marschall_guitar_c5, 255, 254, 0, 48	@ 127/ 30/  1/125/ 64
