	.align 2
voicegroup283:: @ used in: icirrus; opelucid_black
	voice_keysplit voicegroupInst5, KeySplitTable97	@ harpsichord || 62 | 72
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst7, KeySplitTable40	@ marimba | 55 | 67	@ -55 not used
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst14, KeySplitTable92	@ accordion || 68	@ -56 not used
	voice_keysplit voicegroupInst15, KeySplitTable87	@ nylon string guitar | 52 | 60	@ 70+ not used
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst58, KeySplitTable8	@ electric bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst44, KeySplitTable96	@ orchestra strings | 46 | 54 | 63	@ -54; 72+ not used
	voice_keysplit voicegroupInst45, KeySplitTable46	@ violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst46, KeySplitTable98	@ resonant synth (124 release) || 79
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst55, KeySplitTable88	@ flute 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit_all voicegroupDrum14	@ drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_bw_sync_lead_b1, 255, 64, 227, 88	@ 127/125/120/124/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_dancefloor_bass_fs1, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_vocoder_58, 255, 0, 255, 178	@ 127/127/127/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_vocoder_59, 255, 0, 255, 178	@ 127/127/127/120/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_bw_solo_trumpet_c5, 255, 0, 255, 178	@ 127/127/127/120/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit_all voicegroupDrum10	@ drums
