	.align 2
voicegroupDrum7:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64
	voice_directsound 49, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 50, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 51, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 52, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 53, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 54, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 55, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 56, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_sd90_power_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_room_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_room_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80	@ not used
	voice_directsound 63, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 63, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 64, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 65, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 66, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 67, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 68, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 69, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 60, 110, DirectSoundWaveData_hg_031cowbl, 255, 0, 255, 208	@ 127/127/127/116/110
	voice_directsound 60, 40, DirectSoundWaveData_bw_room_crash_cymbal, 255, 251, 0, 208	@ 127/ 62/  0/116/ 40
	voice_directsound 61, 40, DirectSoundWaveData_bw_room_crash_cymbal, 255, 251, 0, 208	@ 127/ 62/  0/116/ 40	@ not used
	voice_directsound 62, 40, DirectSoundWaveData_bw_room_crash_cymbal, 255, 251, 0, 208	@ 127/ 62/  0/116/ 40	@ not used
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90
	voice_directsound 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90
	voice_directsound 58, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 59, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 61, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90
	voice_directsound 62, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 63, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 64, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 65, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 208	@ 127/127/127/116/ 90	@ not used
	voice_directsound 63, 105, DirectSoundWaveData_dp_060conga, 255, 0, 255, 178	@ 127/127/127/120/105
